[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/correct"
  to = "/.netlify/functions/correct"
  status = 200

[[redirects]]
  from = "/api/music"
  to = "/.netlify/functions/music"
  status = 200
